import 'package:hive/hive.dart';

part 'india_state.g.dart';

@HiveType(typeId: 42)
enum IndiaState {
  @HiveField(1)
  AndhraPradesh,
  @HiveField(2)
  ArunachalPradesh,
  @HiveField(3)
  Assam,
  @HiveField(4)
  Bihar,
  @HiveField(5)
  Chhattisgarh,
  @HiveField(6)
  Goa,
  @HiveField(7)
  Gujrat,
  @HiveField(8)
  Haryana,
  @HiveField(9)
  HimachalPradesh,
  @HiveField(10)
  Jharkhand,
  @HiveField(11)
  Karnataka,
  @HiveField(12)
  Kerla,
  @HiveField(13)
  MadhyaPradesh,
  @HiveField(14)
  Maharashtra,
  @HiveField(15)
  Manipur,
  @HiveField(16)
  Meghalaya,
  @HiveField(17)
  Mizoram,
  @HiveField(18)
  Nagaland,
  @HiveField(19)
  Odisha,
  @HiveField(20)
  Punjab,
  @HiveField(21)
  Rajasthan,
  @HiveField(22)
  Sikkim,
  @HiveField(23)
  TamilNadu,
  @HiveField(24)
  Telangana,
  @HiveField(25)
  Tripura,
  @HiveField(26)
  UttarPradesh,
  @HiveField(27)
  Uttarakhand,
  @HiveField(28)
  WestBengal,
  @HiveField(29)
  AndamanAndNicobarIslands,
  @HiveField(30)
  Chandigarh,
  @HiveField(31)
  DadraAndNagarHaveliAndDamanAndDiu,
  @HiveField(32)
  Delhi,
  @HiveField(33)
  JammuAndKashmir,
  @HiveField(34)
  Ladakh,
  @HiveField(35)
  Lakshadweep,
  @HiveField(36)
  Puducherry,
  @HiveField(37)
  State,
}
